{% set version = "0.8.0" %}

package:
  name: stdlib-list
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stdlib-list/stdlib-list-{{ version }}.tar.gz
  sha256: a1e503719720d71e2ed70ed809b385c60cd3fb555ba7ec046b96360d30b16d9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - sphinx

test:
  imports:
    - stdlib_list

about:
  home: http://github.com/jackmaney/python-stdlib-list
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A list of Python Standard Libraries (2.6-7, 3.2-5)
  dev_url: http://github.com/jackmaney/python-stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
