{% set version = "0.4.0" %}
{% set sha256 = "c789a699db288cb20119b066bfca56567a5cd5dcc5451b61b9b43d91a6b8598b" %}

package:
  name: stdlib-list
  version: {{ version }}

source:
  fn: stdlib_list-{{ version }}.tar.gz
  url: https://github.com/jackmaney/python-stdlib-list/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sphinx

test:
  imports:
    - stdlib_list

about:
  home: http://github.com/jackmaney/python-stdlib-list
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A list of Python Standard Libraries (2.6-7, 3.2-5)
  dev_url: http://github.com/jackmaney/python-stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
