{% set name = "stdlib-list" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stdlib_list-{{ version }}.tar.gz
  sha256: 95ebd1d73da9333bba03ccc097f5bac05e3aa03e6822a0c0290f87e1047f1857

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - stdlib_list
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/jackmaney/python-stdlib-list
  summary: A list of Python Standard Libraries (2.7 through 3.12).
  dev_url: https://github.com/pypi/stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
    - xhochy
