{% set name = "stdlib-list" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stdlib_list-{{ version }}.tar.gz
  sha256: 6519c50d645513ed287657bfe856d527f277331540691ddeaf77b25459964a14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7

test:
  imports:
    - stdlib_list
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A list of Python Standard Libraries (2.7 through 3.12).
  dev_url: https://github.com/pypi/stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
