{% set version = "0.7.0" %}

package:
  name: stdlib-list
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stdlib-list/stdlib-list-{{ version }}.tar.gz
  sha256: 66c1c1724a12667cdb35be9f43181c3e6646c194e631efaaa93c1f2c2c7a1f7f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - sphinx
    - functools32  # [py2k]

test:
  imports:
    - stdlib_list

about:
  home: http://github.com/jackmaney/python-stdlib-list
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A list of Python Standard Libraries (2.6-7, 3.2-5)
  dev_url: http://github.com/jackmaney/python-stdlib-list
  doc_url: https://jackmaney.github.io/python-stdlib-list

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - marshall245
    - jackmaney
